import './globals.css';
import { Inter } from "next/font/google";
import Navbar from '../components/navbar/Navbar';
import Footer from '../components/footer/Footer';
import React, { ReactNode } from 'react';

const inter = Inter({ subsets: ["latin"] });

export const metadata: { title: string, description: string } = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}